config/routes.rb
Chifan::Application.routes.draw do

  resources :bets

  resources :gamblegames

  resources :comments

	get "scores/submit"
  resources :scores

  resources :games

  get "incharges/create"
  get "incharges/index"
  get "incharges/update"

  resources :lunchs
  
	
	
  get "lunch/show"
  get "mainpage/home"
  get "mainpage/newlunch"

  root :to =>'Lunchs#index'
  
  devise_for :users
  resources :users
  resources :lunches
  resources :fangroups
  resources :incharges
  resources :attrelationships
  resources :followrelationships
	resources :games

  
  

end

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :game_id, :record, :user_id
  
  belongs_to :user
  belongs_to :game
  
  default_scope order: 'scores.record ASC'
  
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

	def submit
	   @score = Score.new
		 @score.game_id = params[:game_id]
		 @score.user_id = current_user.id
		 @score.record = params[:record]
		@score.save if @score.record > 6.3
		
		redirect_to :back
	end
	
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :record %><br />
    <%= f.text_field :record %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<% if current_user.email == "ji.x.li@oracle.com" %>
	<h1>Editing score</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Show', @score %> |
	<%= link_to 'Back', scores_path %>
<% else %>
	<h1><%= current_user.name %> is not authorized to access this page</h1>
<% end %>

app/views/scores/index.html.erb
<% if current_user.email == "ji.x.li@oracle.com" %>
	<h1>Listing scores</h1>
	
	<table>
	  <tr>
	    <th>Game</th>
	    <th>User</th>
	    <th>Record</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @scores.each do |score| %>
	  <tr>
	    <td><%= score.game_id %></td>
	    <td><%= score.user_id %></td>
	    <td><%= score.record %></td>
	    <td><%= link_to 'Show', score %></td>
	    <td><%= link_to 'Edit', edit_score_path(score) %></td>
	    <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
	</table>
	
	<br />
	
	<%= link_to 'New Score', new_score_path %>
<% else %>
	<h1><%= current_user.name %> is not authorized to access this page</h1>
<% end %>

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @score.game_id %>
</p>

<p>
  <b>User:</b>
  <%= @score.user_id %>
</p>

<p>
  <b>Record:</b>
  <%= @score.record %>
</p>


<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>