config/routes.rb
Chifan::Application.routes.draw do

  resources :bets

  resources :gamblegames

  resources :comments

	get "scores/submit"
  resources :scores

  resources :games

  get "incharges/create"
  get "incharges/index"
  get "incharges/update"

  resources :lunchs
  
	
	
  get "lunch/show"
  get "mainpage/home"
  get "mainpage/newlunch"

  root :to =>'Lunchs#index'
  
  devise_for :users
  resources :users
  resources :lunches
  resources :fangroups
  resources :incharges
  resources :attrelationships
  resources :followrelationships
	resources :games

  
  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  attr_accessible :gamble_id, :selection, :user_id
	
	belongs_to :gamble, foreign_key: "gamble_id", class_name: "Gamblegame"
	belongs_to :user, foreign_key: "user_id", class_name: "User"
	
	def winnercount
		if self.gamble.result == nil
			return 0 
		end
		c = 0
		self.gamble.bets.each do |b|
			c = c + 1 if b.selection == self.gamble.result
		end
		return c
	end
	
	def maywinnercount
		c = 0
		self.gamble.bets.each do |b|
			c = c + 1 if b.selection == self.selection
		end
		return c
	end
	
	def winprice
		if self.gamble.result == nil
			return 0 
		end
		if self.gamble.result != self.selection
			return 0 
		end
		return (self.gamble.bets.count * 1.0 / winnercount).round(2)
	end
	
	def maywinprice
		return ((self.gamble.bets.count * 1.0 / maywinnercount) - 1).round(2)
	end
	
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bets }
    end
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
    @bet = Bet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/new
  # GET /bets/new.json
  def new
    @bet = Bet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bet }
    end
  end

  # GET /bets/1/edit
  def edit
    @bet = Bet.find(params[:id])
  end

  # POST /bets
  # POST /bets.json
  def create
		nb = Bet.new
		nb.user_id = params[:user_id]	
		nb.gamble_id = params[:gamble_id]	
		nb.selection = params[:selection]
		nb.save
				
		redirect_to :back
  end

  # PUT /bets/1
  # PUT /bets/1.json
  def update
    @bet = Bet.find(params[:id])

    respond_to do |format|
      if @bet.update_attributes(params[:bet])
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy

    respond_to do |format|
      format.html { redirect_to bets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for(@bet) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :gamble_id %><br />
    <%= f.number_field :gamble_id %>
  </div>
  <div class="field">
    <%= f.label :selection %><br />
    <%= f.number_field :selection %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <tr>
    <th>User</th>
    <th>Gamble</th>
    <th>Selection</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bets.each do |bet| %>
  <tr>
    <td><%= bet.user_id %></td>
    <td><%= bet.gamble_id %></td>
    <td><%= bet.selection %></td>
    <td><%= link_to 'Show', bet %></td>
    <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
    <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @bet.user_id %>
</p>

<p>
  <b>Gamble:</b>
  <%= @bet.gamble_id %>
</p>

<p>
  <b>Selection:</b>
  <%= @bet.selection %>
</p>


<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>