config/routes.rb
Chifan::Application.routes.draw do

  resources :bets

  resources :gamblegames

  resources :comments

	get "scores/submit"
  resources :scores

  resources :games

  get "incharges/create"
  get "incharges/index"
  get "incharges/update"

  resources :lunchs
  
	
	
  get "lunch/show"
  get "mainpage/home"
  get "mainpage/newlunch"

  root :to =>'Lunchs#index'
  
  devise_for :users
  resources :users
  resources :lunches
  resources :fangroups
  resources :incharges
  resources :attrelationships
  resources :followrelationships
	resources :games

  
  

end

app/models/gamblegame.rb
class Gamblegame < ActiveRecord::Base
  attr_accessible :description, :options, :result, :user_id
	
	belongs_to :user
	
	has_many :bets, foreign_key: "gamble_id"
	
	def Gamblegame.currentgambles
		cg = Array.new
		Gamblegame.all.each do |g|
			if g.result == nil then
				cg << g
			end
		end
		return cg
	end
	
	def Gamblegame.usersgambles user
		cg = Array.new
		Gamblegame.all.each 
	end
	
	def optionarray
		return self.options.split("#")
	end
	
	def usernotinvolved? user
		notinvolved = true
		self.bets.each do |b|
			notinvolved = false if b.user == user
		end
		return notinvolved
	end
	
	def usercount selection
		c = 0
		self.bets.each do |b|
			if b.selection == selection
				c = c + 1
			end
		end
		return c
	end
	
	def haswinner?
		if self.result > 0 
			self.bets.each do |b|
				if b.selection == self.result
					return true
				end
			end
			return false
		else
			return false
		end
	end
	
end

app/controllers/gamblegames_controller.rb
class GamblegamesController < ApplicationController
  # GET /gamblegames
  # GET /gamblegames.json
  def index
    @gamblegames = Gamblegame.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gamblegames }
    end
  end

  # GET /gamblegames/1
  # GET /gamblegames/1.json
  def show
    @gamblegame = Gamblegame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gamblegame }
    end
  end

  # GET /gamblegames/new
  # GET /gamblegames/new.json
  def new
    @gamblegame = Gamblegame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gamblegame }
    end
  end

  # GET /gamblegames/1/edit
  def edit
    @gamblegame = Gamblegame.find(params[:id])
  end

  # POST /gamblegames
  # POST /gamblegames.json
  def create
    @gamblegame = Gamblegame.new(params[:gamblegame])

    respond_to do |format|
      if @gamblegame.save
        format.html { redirect_to @gamblegame, notice: 'Gamblegame was successfully created.' }
        format.json { render json: @gamblegame, status: :created, location: @gamblegame }
      else
        format.html { render action: "new" }
        format.json { render json: @gamblegame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gamblegames/1
  # PUT /gamblegames/1.json
  def update
    @gamblegame = Gamblegame.find(params[:id])

    respond_to do |format|
      if @gamblegame.update_attributes(params[:gamblegame])
        format.html { redirect_to @gamblegame, notice: 'Gamblegame was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gamblegame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamblegames/1
  # DELETE /gamblegames/1.json
  def destroy
    @gamblegame = Gamblegame.find(params[:id])
    @gamblegame.destroy

    respond_to do |format|
      format.html { redirect_to gamblegames_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gamblegames_helper.rb
module GamblegamesHelper
end

app/views/gamblegames/_form.html.erb
<%= form_for(@gamblegame) do |f| %>
  <% if @gamblegame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamblegame.errors.count, "error") %> prohibited this gamblegame from being saved:</h2>

      <ul>
      <% @gamblegame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_field :options %>
  </div>
  <div class="field">
    <%= f.label :result %><br />
    <%= f.number_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamblegames/edit.html.erb
<h1>Editing gamblegame</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamblegame %> |
<%= link_to 'Back', gamblegames_path %>

app/views/gamblegames/index.html.erb
<h1>Listing gamblegames</h1>

<table>
  <tr>
    <th>User</th>
    <th>Description</th>
    <th>Options</th>
    <th>Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gamblegames.each do |gamblegame| %>
  <tr>
    <td><%= gamblegame.user_id %></td>
    <td><%= gamblegame.description %></td>
    <td><%= gamblegame.options %></td>
    <td><%= gamblegame.result %></td>
    <td><%= link_to 'Show', gamblegame %></td>
    <td><%= link_to 'Edit', edit_gamblegame_path(gamblegame) %></td>
    <td><%= link_to 'Destroy', gamblegame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gamblegame', new_gamblegame_path %>

app/views/gamblegames/new.html.erb
<h1>New gamblegame</h1>

<%= render 'form' %>

<%= link_to 'Back', gamblegames_path %>

app/views/gamblegames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @gamblegame.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @gamblegame.description %>
</p>

<p>
  <b>Options:</b>
  <%= @gamblegame.options %>
</p>

<p>
  <b>Result:</b>
  <%= @gamblegame.result %>
</p>


<%= link_to 'Edit', edit_gamblegame_path(@gamblegame) %> |
<%= link_to 'Back', gamblegames_path %>